# Generated by Django 5.1.3 on 2025-11-07 07:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique voucher code",
                        max_length=50,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable voucher name",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the voucher",
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("USED", "Used"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Current status of the voucher",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when voucher becomes valid",
                        verbose_name="valid from",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        help_text="Date when voucher expires",
                        verbose_name="valid until",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this voucher can be used (null = unlimited)",
                        null=True,
                        verbose_name="usage limit",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current number of times voucher has been used",
                        verbose_name="usage count",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this voucher",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "voucher",
                "verbose_name_plural": "vouchers",
                "db_table": "vouchers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FixedAmountVoucher",
            fields=[
                (
                    "voucher_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vouchers.voucher",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed amount to discount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum purchase amount required to use voucher",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="minimum purchase amount",
                    ),
                ),
            ],
            options={
                "verbose_name": "fixed amount voucher",
                "verbose_name_plural": "fixed amount vouchers",
            },
            bases=("vouchers.voucher",),
        ),
        migrations.CreateModel(
            name="FreeShippingVoucher",
            fields=[
                (
                    "voucher_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vouchers.voucher",
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum purchase amount required to use voucher",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="minimum purchase amount",
                    ),
                ),
                (
                    "max_shipping_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum shipping amount that will be covered",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="maximum shipping amount",
                    ),
                ),
            ],
            options={
                "verbose_name": "free shipping voucher",
                "verbose_name_plural": "free shipping vouchers",
            },
            bases=("vouchers.voucher",),
        ),
        migrations.CreateModel(
            name="PercentageDiscountVoucher",
            fields=[
                (
                    "voucher_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vouchers.voucher",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage to discount (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="discount percentage",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount (optional cap)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="maximum discount amount",
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum purchase amount required to use voucher",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="minimum purchase amount",
                    ),
                ),
            ],
            options={
                "verbose_name": "percentage discount voucher",
                "verbose_name_plural": "percentage discount vouchers",
            },
            bases=("vouchers.voucher",),
        ),
        migrations.CreateModel(
            name="VoucherUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The purchase amount when voucher was used",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="purchase amount",
                    ),
                ),
                (
                    "discount_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The actual discount amount applied",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="discount applied",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when voucher was used",
                        verbose_name="used at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who used the voucher",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        help_text="The voucher that was used",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="vouchers.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "voucher usage",
                "verbose_name_plural": "voucher usages",
                "db_table": "voucher_usages",
                "ordering": ["-used_at"],
            },
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["code", "status"], name="vouchers_code_3896c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["status", "valid_from", "valid_until"],
                name="vouchers_status_3abbcf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voucherusage",
            index=models.Index(
                fields=["voucher", "user"], name="voucher_usa_voucher_db8d9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucherusage",
            index=models.Index(
                fields=["user", "used_at"], name="voucher_usa_user_id_a1d0a3_idx"
            ),
        ),
    ]
